//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy_Licensing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Easy_Licensing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more provided hardware details did not match the license details: {0}..
        /// </summary>
        internal static string FailedHardwareIdentity {
            get {
                return ResourceManager.GetString("FailedHardwareIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License does not allow running within a virtual machine.
        /// </summary>
        internal static string FailedHardwareVirtualBlocked {
            get {
                return ResourceManager.GetString("FailedHardwareVirtualBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License requires running within a virtual machine.
        /// </summary>
        internal static string FailedHardwareVirtualRequired {
            get {
                return ResourceManager.GetString("FailedHardwareVirtualRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided product key was invalid..
        /// </summary>
        internal static string FailedProductKey {
            get {
                return ResourceManager.GetString("FailedProductKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided license expired at {0}..
        /// </summary>
        internal static string FailedTimeLock {
            get {
                return ResourceManager.GetString("FailedTimeLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more provided user details did not match the license details: {0}..
        /// </summary>
        internal static string FailedUserIdentity {
            get {
                return ResourceManager.GetString("FailedUserIdentity", resourceCulture);
            }
        }
    }
}
